server:
  port: 8081
spring:
  application:
    name: first-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/
  instance:
#    hostname: firstclient
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
first-client:
  ribbon:
