server:
  port: 8081
spring:
  application:
    name: first_client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8079/eureka/
  instance:
    hostname: first_client
