server:
  port: 8082
spring:
  application:
    name: secondclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8079/eureka/
  instance:
    hostname: secondclient
    instance-id: secondclient:8082